### PR TITLE
Fix the UI from split view to full-sized view 

### LINKED ISSUE #122: Fix the UI from a split view to a full-sized view

### PR DESCRIPTION
**Pull request by baglaanugrah**
Fixes #122 and #115

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ExitCommand.java [hunk 1]
```diff
@@ -8,6 +8,8 @@
 public class ExitCommand extends Command {
 
     public static final String COMMAND_WORD = "exit";
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Exits the application.\n"
```
Comment (15-Manya) [inline src/main/java/seedu/address/logic/commands/ExitCommand.java]: Is this required? The usage message isn't shown because it would only read the command when `exit` keyword is used
